adding compiler binary path

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -22,10 +22,25 @@ cache:
 jobs:
   include:
     - script:
+        - export CC=/usr/local/opt/llvm\@6/bin/clang
+        - export CXX=/usr/local/opt/llvm\@6/bin/clang++
         - echo "BUILDING KERNEL"
         - conan create . includeos/latest -pr clang-6.0-macos-x86_64
         - echo "BUILDING LiveUpdate"
         - conan create lib/LiveUpdate includeos/latest -pr clang-6.0-macos-x86_64
+        - git clone https://github.com/includeos/hello_world
+        - conan install hello_world -pr clang-6.0-macos-x86_64
+        - source activate.sh
+        - cmake hello_world
+        - cmake --build .
+        - gtimeout 7 boot hello > hello_log.txt || true
+        - |
+          if grep -F "Running [ Hello world - OS included ]" hello_log.txt
+          then
+            echo "Hello World -  Success! :)"
+          else
+            echo "Failed :("
+          fi
       name: "clang-6.0-x86_64"
 
 before_install:
@@ -35,3 +50,6 @@ install:
   - conan config install https://github.com/includeos/conan_config.git
   - conan --version
   - clang --version
+
+after_script:
+  - source deactivate.sh
