travis-ci: adding build step

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -26,7 +26,19 @@ jobs:
         - conan create . includeos/latest -pr clang-6.0-macos-x86_64
         - echo "BUILDING LiveUpdate"
         - conan create lib/LiveUpdate includeos/latest -pr clang-6.0-macos-x86_64
-      name: "clang-6.0-x86_64"
+        - conan install hello_world -pr clang-6.0-macos-x86_64
+        - source activate.sh
+        - cmake hello_world
+        - cmake --build .
+        - gtimeout 7 boot hello > hello_log.txt || true
+        - |
+          if grep -F "Running [ Hello world - OS included ]" hello_log.txt
+          then
+            echo "Hello World -  Success! :)"
+          else
+            echo "Failed :("
+          fi
+            name: "clang-6.0-x86_64"
 
 before_install:
   - git fetch --tags https://github.com/includeos/IncludeOS.git
@@ -35,3 +47,9 @@ install:
   - conan config install https://github.com/includeos/conan_config.git
   - conan --version
   - clang --version
+
+before_script:
+  - git clone https://github.com/includeos/hello_world
+
+after_script:
+  - source deactivate.sh
